### ISSUE TITLE
como actualizo popup lyrics ya lo tenia instalado 

### ISSUE THREAD

**Issue by Maguz0** [Patrick-orz/PopupLyrics-Plus#11]
como actualizo popup lyrics la actualizacion salio hace 2 dias y ya tenia instalado popup entonces que prosigue es todo y gracias por arreglar errores que tenia

**Comment by Patrick-orz** [comment]
Hola Maguz0,

I see that you have posted an issue in Spanish, please try to use english or Chinese only from now on, as I don't understand any other languages.  Use google translate if necessary.

I think you are asking about how to start the plugin once it is installed. Assuming you have followed the installation steps correctly, which is getting the latest version from the release tab and putting the js file in the spicetify extensions folder, there should be a ui added to the top left of spotify, just like the original popup lyrics:
![image](https://github.com/user-attachments/assets/53348414-ec46-413c-a2ad-da240e909808)
_I have two ui here because I have original popuplyrics and popuplyrics plus enabled at the same time_

The one with a karoake mic on it is the ui I am referring to, it should say Popup Lyrics Plus on hover. Left clicking it opens the lyrics window, right clicking opens the options menu.

If there is no UI available, it is probably an issue with installation, make sure you follow the steps correctly.

This issue would be closed unless it persists.

**Comment by Maguz0** [comment]
I don't mean that, I mean that I already have the previous version of popup lyrics installed and I wanted to update it, but how do I update it? And thank you for understanding that I only understand Spanish.

**Comment by Patrick-orz** [comment]
You simply replace the previous popupLyricsPlus.js file with the new one. You would know that you have the latest version if all features are there.

**Comment by Maguz0** [comment]
thank you

**Comment by Maguz0** [comment]
problems duplicates
![Spotify premium 2 nov  2024 11_49_28](https://github.com/user-attachments/assets/9534c697-4671-4d31-a68b-89b2b8ea6f82)
